#########################
### CloudFlare Config ###
#########################
token: your_cloudflare_api_token # Your Cloudflare API token for authentication.
zone-identifier: your_zone_identifier # The Zone ID of your domain on Cloudflare.
cloudflare-dns-record:
  # The required fields are the identifier, content, name, and type.
  identifier: your_dns_record_identifier # The Identifier for the specific DNS record you want to dnsclient.
  name: your_domain # The domain name for the DNS record.
  type: A # The type of DNS record (e.g., A, AAAA, CNAME, etc.).
  proxied: false # Whether the record is receiving the performance and security benefits of Cloudflare.
  comment: your_comment # Comments or notes about the DNS record. This field has no effect on DNS responses.
  tags: [ tag1, tag2 ] # Custom tags for the DNS record. This field has no effect on DNS responses.
  ttl: 1 # Time To Live (TTL) of the DNS record in seconds. Setting to 1 means 'automatic'. Value must be between 60 and 86400, with the minimum reduced to 30 for Enterprise zones.